create table if not exists application (
    id bigint generated by default as identity primary key,
    unique_identifier varchar(50) not null unique,
    name varchar(80) not null
);

create table if not exists theme (
    id bigint generated by default as identity primary key,
    unique_identifier varchar(50) not null unique,
    name varchar(80) not null
);

create table if not exists wallpaper (
    id bigint generated by default as identity primary key,
    unique_identifier varchar(100) not null unique,
    name varchar(120) not null
);

create table if not exists menu (
    id bigint generated by default as identity primary key,
    unique_identifier varchar(50) not null unique,
    name varchar(80) not null
);

create table if not exists account (
    id bigint generated by default as identity primary key,
    unique_identifier varchar(50) not null unique,
    name varchar(80) not null,
    username varchar(50) not null unique,
    password varchar(255) not null,
    menu_id bigint unique,
    theme_id bigint,
    wallpaper_id bigint,
    constraint fk_account_menu foreign key (menu_id) references menu (id),
    constraint fk_account_theme foreign key (theme_id) references theme (id),
    constraint fk_account_wallpaper foreign key (wallpaper_id) references wallpaper (id)
);

create table if not exists menu_item (
    id bigint generated by default as identity primary key,
    unique_identifier varchar(50) not null unique,
    name varchar(80) not null,
    menu_id bigint not null,
    application_id bigint,
    parent_id bigint,
    constraint fk_menu_item_menu foreign key (menu_id) references menu (id),
    constraint fk_menu_item_application foreign key (application_id) references application (id),
    constraint fk_menu_item_parent foreign key (parent_id) references menu_item (id)
);

create table if not exists account_applications (
    account_id bigint not null,
    application_id bigint not null,
    primary key (account_id, application_id),
    constraint fk_account_applications_account foreign key (account_id) references account (id),
    constraint fk_account_applications_application foreign key (application_id) references application (id)
);
